#!/bin/sh
git checkout master
rm -rf scratch
mkdir scratch
ant doc
mv *reports scratch/
ant clean
git checkout gh-pages
mv scratch/* ./
git add .
git commit -m "auto doc regen"
git push origin gh-pages
git checkout master
